devtools::load_all()
configureMlr(on.par.without.desc = "warn")
fn = makeRosenbrockFunction(4)
ctrl = makeMBOControl(propose.points = 4, store.model.at = 0:20)
ctrl = setMBOControlInfill(ctrl, crit = "ei")
ctrl = setMBOControlMultiPoint(ctrl, method = "cl", cl.lie = max)
ctrl = setMBOControlTermination(ctrl, iters = 6)
lrn = makeLearner("regr.km", nugget.stability = 10^-8, covtype = "matern5_2", predict.type = "se", multistart = 3)
des = generateDesign(par.set = smoof::getParamSet(fn), n = 10)
res = mbo(fn, design = des, learner = lrn, control = ctrl)

grid = generateGridDesign(par.set = smoof::getParamSet(fn), resolution = 3)
pred = predict(xx.models[[2]], newdata = grid)
sd(getPredictionResponse(pred))
