BBOB_FIDS = 1:2
BBOB_DIMS = c(2)
BUDGET = function(d) d * 100

MBO_SURROGATE = "regr.km"
MBO_SURROGATE_VALS = list()
MBO_INFILL_CRIT = "ei"

MBO_INIT_DES_SIZE = function(d) 10 * d
MBO_ITERS = function(d) BUDGET(d) - MBO_INIT_DES_SIZE(d)

MBO_FOCUSSEARCH_RESTARTS = 2L
MBO_FOCUSSEARCH_ITERS = 2L
MBO_FOCUSSEARCH_POINTS = 500L


