configureMlr(on.learner.error = "warn")

CV_FOLDS_OUTER = 5L
TUNE_BUDGET = 100L

# IRACE_INNER_SPLIT = 0.8

MBO_INIT_DES_SIZE = round(TUNE_BUDGET / 3)
MBO_ITERS = TUNE_BUDGET - MBO_INIT_DES_SIZE
# MBO_INIT_DES_SIZE = 20
# MBO_ITERS = 1

MBO_SURROGATE = "regr.kknn"

MBO_FOCUSSEARCH_RESTARTS = 2L
MBO_FOCUSSEARCH_ITERS = 2L
MBO_FOCUSSEARCH_POINTS = 500L




