context("asyn MBO")

test_that("asyn MBO works", {
  save.file = file.path(tempdir(), "asyn", "mbo.RData")
  ctrl = makeMBOControl(schedule.method = "asyn", save.file.path = save.file)
  ctrl = setMBOControlTermination(ctrl, iters = 20L, max.evals = 20L)
  ctrl = setMBOControlInfill(control = ctrl, crit = "cb", crit.cb.lambda = 2, opt.focussearch.maxit = 2L, opt.focussearch.points = 50L)
  ctrl = setMBOControlMultiPoint(ctrl, method = "cb")
  surrogat.learner = makeLearner("regr.randomForest", predict.type = "se", ntree = 50, ntree.for.se = 20)
  if (interactive()) parallelMap::parallelStartMulticore(4)
  or = mbo(fun = testf.fsphere.2d, design = testd.fsphere.2d, learner = surrogat.learner, control = ctrl)
  if (interactive()) parallelMap::parallelStop()
  unlink(dirname(save.file), recursive = TRUE, force = TRUE)
  op.df = as.data.frame(or$opt.path)
  expect_true(nrow(op.df) >= 20)
  expect_true(all(!is.na(op.df$train.time[11:20])))
  expect_true(all(!is.na(op.df$multipoint.cb.lambda[11:20])))
})

test_that("asyn MBO works with CL", {
  save.file = file.path(tempdir(), "asyn", "mbo.RData")
  ctrl = makeMBOControl(schedule.method = "asyn", save.file.path = save.file)
  ctrl = setMBOControlTermination(ctrl, iters = 20L, max.evals = 20L)
  ctrl = setMBOControlInfill(control = ctrl, crit = "ei", opt.focussearch.maxit = 2L, opt.focussearch.points = 50L)
  ctrl = setMBOControlMultiPoint(ctrl, method = "cl")
  surrogat.learner = makeLearner("regr.km", predict.type = "se")
  if (interactive()) parallelMap::parallelStartMulticore(4)
  or = mbo(fun = testf.fsphere.2d, design = testd.fsphere.2d, learner = surrogat.learner, control = ctrl)
  if (interactive()) parallelMap::parallelStop()
  unlink(dirname(save.file), recursive = TRUE, force = TRUE)
  op.df = as.data.frame(or$opt.path)
  expect_true(nrow(op.df) >= 20)
  expect_true(all(!is.na(op.df$train.time[11:20])))
  expect_true(all(!is.na(op.df$ei[11:20])))
})
