# GENERAL
DIM_X = 2L
DIM_Y = 2L
FEVALS = 20L
REPLS = 1L
INIT_DESIGN_POINTS = 10L
PARALLEL_PROP_POINTS = 5L
stopifnot((FEVALS - INIT_DESIGN_POINTS) %% PARALLEL_PROP_POINTS == 0)

# FOCUSSEARCH
FOCUSSEARCH_POINTS = 10
FOCUSSEARCH_MAXIT = 1
FOCUSSEARCH_RESTARTS = 1

# nsga2 baseline comparison
BASELINE_NSGA2_POPSIZE = 20L # must be a multiple of 4
stopifnot(BASELINE_NSGA2_POPSIZE %% 4 == 0)
stopifnot(FEVALS %% BASELINE_NSGA2_POPSIZE == 0)
BASELINE_NSGA2_GENERATIONS1 = FEVALS / BASELINE_NSGA2_POPSIZE
BASELINE_NSGA2_GENERATIONS2 = BASELINE_NSGA2_GENERATIONS1 * 10L

# parego
stopifnot((FEVALS - INIT_DESIGN_POINTS) %% PARALLEL_PROP_POINTS == 0)
# ITERS = (FEVALS - INIT_DESIGN_POINTS) / PROP_POINTS

# mspot
MSPOT_NSGA2_GENERATIONS = 2L
MSPOT_NSGA2_POPSIZE = 8L

# r2 indicator
dim1 = seq(0, 1, 0.01)
dim2 = 1 - dim1
WEIGHTS = rbind(dim1, dim2)
